services:
  giropops-senhas:
    image: zenardi/giropops-senhas:4.0
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    volumes:
      - strigus:/strigus
    networks:
      - giropops

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - giropops

volumes:
  strigus:

networks:
  giropops:
    driver: bridge