services:
  giropops-senhas:
    image: zenardi/giropops-senhas:4.0
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 256M
        limits:
          cpus: '0.50'
          memory: 512M
    environment:
      - REDIS_HOST=redis
    volumes:
      - strigus:/strigus
    networks:
      - giropops
    depends_on:
      - redis

  redis:
    image: redis:latest
    deploy:
      replicas: 3
    # ports:
    #   - "6379:6379"
    networks:
      - giropops

volumes:
  strigus:

networks:
  giropops:
    driver: bridge